/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafiskinterface;

import databas.DBClass;
import java.util.*;
import java.awt.*;
import java.awt.CardLayout;

/**
 *
 * @author Simon the swaglord
 */
public class Main extends javax.swing.JFrame {

    private DBClass infDB;
    HashMap<Integer, String> allPostsList;
    CurrentLoginHolder loginHolder;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        CardLayout card = (CardLayout) pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card4");

        infDB = new DBClass();
        allPostsList = new HashMap<Integer, String>();
        loginHolder = new CurrentLoginHolder();
        
        //Locks the forums which the user doesn't have post rights in.
        lockPostRights();
        
        //int thisID = CurrentLogin.getId();
        //boolean needToChooseTimes1 = isUserInTimeChoicesTable(thisID);
        //boolean needToChooseTimes2 = doesUserHaveNullYesNoInTimeChoices(needToChooseTimes1);
        //showMessageNeedToChooseTimes(needToChooseTimes2);

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Main_MainBackgroundPanel = new javax.swing.JPanel();
        pnl_Main_TopBorderMenu = new javax.swing.JPanel();
        btn_Main_SkapaMote = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_Main_Education = new javax.swing.JButton();
        btn_Main_Research = new javax.swing.JButton();
        btn_Main_Social = new javax.swing.JButton();
        pnl_Main_MainMiddleWindow = new javax.swing.JPanel();
        pnl_MainMiddleWindow_Utbildning = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tpn_Main_MainMiddleWindow_Education_MainPane1 = new javax.swing.JTabbedPane();
        tpn_Main_MainMiddleWindow_Education_MainPane = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow6 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_Education = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        pnl_MainMiddleWindow_Forskning = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tpn_Main_MainMiddleWindow_Research_MainPane = new javax.swing.JTabbedPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1 = new javax.swing.JPanel();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow = new javax.swing.JTextArea();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2 = new javax.swing.JPanel();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow = new javax.swing.JTextArea();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3 = new javax.swing.JPanel();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow = new javax.swing.JTextArea();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4 = new javax.swing.JPanel();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow = new javax.swing.JTextArea();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5 = new javax.swing.JPanel();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow = new javax.swing.JTextArea();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6 = new javax.swing.JPanel();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow = new javax.swing.JTextArea();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAll = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        pnl_MainMiddleWindow_Social = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tpn_Main_MainMiddleWindow_Social = new javax.swing.JTabbedPane();
        tpn_Main_MainMiddleWindow_Social_Pane1 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow7 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_Social = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_Main_Avsluta = new javax.swing.JButton();
        btn_Main_Loggaut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnl_Main_MainBackgroundPanel.setBackground(new java.awt.Color(102, 102, 102));

        pnl_Main_TopBorderMenu.setBackground(new java.awt.Color(255, 255, 255));

        btn_Main_SkapaMote.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_SkapaMote.setText("Skapa möte ");
        btn_Main_SkapaMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_SkapaMoteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Se möten");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Main_Education.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_Education.setText("Utbildning");
        btn_Main_Education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_EducationActionPerformed(evt);
            }
        });

        btn_Main_Research.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_Research.setText("Forskning");
        btn_Main_Research.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_ResearchActionPerformed(evt);
            }
        });

        btn_Main_Social.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_Social.setText("Social");
        btn_Main_Social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_SocialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Main_TopBorderMenuLayout = new javax.swing.GroupLayout(pnl_Main_TopBorderMenu);
        pnl_Main_TopBorderMenu.setLayout(pnl_Main_TopBorderMenuLayout);
        pnl_Main_TopBorderMenuLayout.setHorizontalGroup(
            pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_TopBorderMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_Main_Education, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Main_Research, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Main_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btn_Main_SkapaMote)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Main_TopBorderMenuLayout.setVerticalGroup(
            pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_TopBorderMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Main_Education, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Main_Social, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_Main_TopBorderMenuLayout.createSequentialGroup()
                        .addGroup(pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Main_SkapaMote, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_Main_Research, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_Main_TopBorderMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Main_SkapaMote, jButton1});

        pnl_Main_MainMiddleWindow.setBackground(new java.awt.Color(102, 102, 102));
        pnl_Main_MainMiddleWindow.setLayout(new java.awt.CardLayout());

        pnl_MainMiddleWindow_Utbildning.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setText("Utbildning");

        tpn_Main_MainMiddleWindow_Education_MainPane1.setPreferredSize(new java.awt.Dimension(529, 100));

        tpn_Main_MainMiddleWindow_Education_MainPane.setMinimumSize(new java.awt.Dimension(529, 100));
        tpn_Main_MainMiddleWindow_Education_MainPane.setPreferredSize(new java.awt.Dimension(529, 393));

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow6.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow6.setText("====================================================================\nTitel: Information om utbildningsseminarium\n\nFörfattare: Jonas.\nDatum: ÅÅÅÅ-MM-DD.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duis id enim vitae quam varius rutrum. In nec vulputate nisl. Aliquam dapibus fermentum convallis.\nSuspendisse potenti. Nunc nulla leo, scelerisque et aliquam ac, fermentum in lacus. Quisque aliquet imperdiet dolor et convallis. Suspendisse lacinia rhoncus vehicula.\nSed a nisi lobortis, iaculis nisi blandit, venenatis ipsum. Etiam ultricies elit quis scelerisque dapibus. Duis sed augue sit amet erat laoreet vestibulum imperdiet quis enim.\n\n====================================================================\n\nTitel: Test \n\nFörfattare: Jonas.\nDatum: ÅÅÅÅ-MM-DD.\n\nVestibulum et lectus ac felis commodo hendrerit eget finibus lorem. Nulla tempor, sapien at finibus commodo, enim quam consectetur purus,\neget gravida lacus arcu sit amet neque. Donec lobortis sodales neque vitae tempor. Aenean vitae ex vitae elit sodales mollis.\n");
        jScrollPane9.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow6);

        btn_Main_MainMiddleWindow_Research_MainPane_Education.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_Education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_EducationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Education_MainPaneLayout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Education_MainPane);
        tpn_Main_MainMiddleWindow_Education_MainPane.setLayout(tpn_Main_MainMiddleWindow_Education_MainPaneLayout);
        tpn_Main_MainMiddleWindow_Education_MainPaneLayout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Education_MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Education_MainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Education_MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Education_MainPaneLayout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_Education))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Education_MainPaneLayout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Education_MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Education_MainPaneLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_Education)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Education_MainPane1.addTab("Utbildning", tpn_Main_MainMiddleWindow_Education_MainPane);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setPreferredSize(new java.awt.Dimension(224, 80));
        jScrollPane20.setViewportView(jTextArea4);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Nyheter");

        javax.swing.GroupLayout pnl_MainMiddleWindow_UtbildningLayout = new javax.swing.GroupLayout(pnl_MainMiddleWindow_Utbildning);
        pnl_MainMiddleWindow_Utbildning.setLayout(pnl_MainMiddleWindow_UtbildningLayout);
        pnl_MainMiddleWindow_UtbildningLayout.setHorizontalGroup(
            pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                        .addComponent(tpn_Main_MainMiddleWindow_Education_MainPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(81, 81, 81)))
                        .addGap(100, 100, 100))))
        );
        pnl_MainMiddleWindow_UtbildningLayout.setVerticalGroup(
            pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpn_Main_MainMiddleWindow_Education_MainPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnl_Main_MainMiddleWindow.add(pnl_MainMiddleWindow_Utbildning, "card2");

        pnl_MainMiddleWindow_Forskning.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setText("Forskning");

        tpn_Main_MainMiddleWindow_Research_MainPane.setPreferredSize(new java.awt.Dimension(529, 100));

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.setMinimumSize(new java.awt.Dimension(529, 100));
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.setPreferredSize(new java.awt.Dimension(529, 393));
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1FocusGained(evt);
            }
        });

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed(evt);
            }
        });

        jScrollPane12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane12FocusGained(evt);
            }
        });

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setRows(5);
        jScrollPane12.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane12)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost)))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 1", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed(evt);
            }
        });

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setRows(5);
        jScrollPane13.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost))
                    .addComponent(jScrollPane13))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 2", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed(evt);
            }
        });

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setRows(5);
        jScrollPane14.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost))
                    .addComponent(jScrollPane14))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 3", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed(evt);
            }
        });

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setRows(5);
        jScrollPane15.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost))
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 4", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed(evt);
            }
        });

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setRows(5);
        jScrollPane18.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost))
                    .addComponent(jScrollPane18))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 5", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed(evt);
            }
        });

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setRows(5);
        jScrollPane19.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost))
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 6", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6);

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setEditable(false);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setColumns(20);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setLineWrap(true);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setRows(5);
        jScrollPane11.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll);

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAll);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAll.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAllLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Alla", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAll);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setMinimumSize(new java.awt.Dimension(104, 80));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nyheter");

        javax.swing.GroupLayout pnl_MainMiddleWindow_ForskningLayout = new javax.swing.GroupLayout(pnl_MainMiddleWindow_Forskning);
        pnl_MainMiddleWindow_Forskning.setLayout(pnl_MainMiddleWindow_ForskningLayout);
        pnl_MainMiddleWindow_ForskningLayout.setHorizontalGroup(
            pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tpn_Main_MainMiddleWindow_Research_MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(183, 183, 183))))
        );
        pnl_MainMiddleWindow_ForskningLayout.setVerticalGroup(
            pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpn_Main_MainMiddleWindow_Research_MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        pnl_Main_MainMiddleWindow.add(pnl_MainMiddleWindow_Forskning, "card3");

        pnl_MainMiddleWindow_Social.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel7.setText("Social");

        tpn_Main_MainMiddleWindow_Social.setPreferredSize(new java.awt.Dimension(529, 100));

        tpn_Main_MainMiddleWindow_Social_Pane1.setMinimumSize(new java.awt.Dimension(529, 100));
        tpn_Main_MainMiddleWindow_Social_Pane1.setPreferredSize(new java.awt.Dimension(529, 393));

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow7.setEditable(false);
        jScrollPane10.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow7);

        btn_Main_MainMiddleWindow_Research_MainPane_Social.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_Social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_SocialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Social_Pane1Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Social_Pane1);
        tpn_Main_MainMiddleWindow_Social_Pane1.setLayout(tpn_Main_MainMiddleWindow_Social_Pane1Layout);
        tpn_Main_MainMiddleWindow_Social_Pane1Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Social_Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Social_Pane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Social_Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Social_Pane1Layout.createSequentialGroup()
                        .addGap(0, 590, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_Social))
                    .addComponent(jScrollPane10))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Social_Pane1Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Social_Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Social_Pane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_Social)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Social.addTab("Social", tpn_Main_MainMiddleWindow_Social_Pane1);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setPreferredSize(new java.awt.Dimension(224, 80));
        jScrollPane17.setViewportView(jTextArea3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Nyheter");

        javax.swing.GroupLayout pnl_MainMiddleWindow_SocialLayout = new javax.swing.GroupLayout(pnl_MainMiddleWindow_Social);
        pnl_MainMiddleWindow_Social.setLayout(pnl_MainMiddleWindow_SocialLayout);
        pnl_MainMiddleWindow_SocialLayout.setHorizontalGroup(
            pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tpn_Main_MainMiddleWindow_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(181, 181, 181))))
        );
        pnl_MainMiddleWindow_SocialLayout.setVerticalGroup(
            pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpn_Main_MainMiddleWindow_Social, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        pnl_Main_MainMiddleWindow.add(pnl_MainMiddleWindow_Social, "card4");

        btn_Main_Avsluta.setText("Avsluta");
        btn_Main_Avsluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_AvslutaActionPerformed(evt);
            }
        });

        btn_Main_Loggaut.setText("Logga ut");
        btn_Main_Loggaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_LoggautActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Main_MainBackgroundPanelLayout = new javax.swing.GroupLayout(pnl_Main_MainBackgroundPanel);
        pnl_Main_MainBackgroundPanel.setLayout(pnl_Main_MainBackgroundPanelLayout);
        pnl_Main_MainBackgroundPanelLayout.setHorizontalGroup(
            pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_TopBorderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Main_Avsluta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_Loggaut)
                .addContainerGap(1182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Main_MainMiddleWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        pnl_Main_MainBackgroundPanelLayout.setVerticalGroup(
            pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                .addComponent(pnl_Main_TopBorderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pnl_Main_MainMiddleWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Main_Avsluta)
                    .addComponent(btn_Main_Loggaut))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_MainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_MainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_Main_AvslutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_AvslutaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_Main_AvslutaActionPerformed

    private void btn_Main_SkapaMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_SkapaMoteActionPerformed
        GrafikHelper.InitieraSkapaMote();
    }//GEN-LAST:event_btn_Main_SkapaMoteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GrafikHelper.InitieraSeMoten();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_Main_EducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_EducationActionPerformed
        CardLayout card = (CardLayout) pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card2");
    }//GEN-LAST:event_btn_Main_EducationActionPerformed

    private void btn_Main_ResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_ResearchActionPerformed
        CardLayout card = (CardLayout) pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card3");
        fillForumWithPost();
    }//GEN-LAST:event_btn_Main_ResearchActionPerformed

    private void btn_Main_SocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_SocialActionPerformed
        CardLayout card = (CardLayout) pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card4");
    }//GEN-LAST:event_btn_Main_SocialActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup1", "Research");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup2", "Research");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup3", "Research");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup4", "Research");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup5", "Research");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup6", "Research");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed

    private void btn_Main_LoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_LoggautActionPerformed
        GrafikHelper.DisposeMain();
        GrafikHelper.InitieraLogIn();
        loginHolder.clearUser();
    }//GEN-LAST:event_btn_Main_LoggautActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_EducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_EducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_EducationActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_SocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_SocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_SocialActionPerformed

    private void jScrollPane12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane12FocusGained

    }//GEN-LAST:event_jScrollPane12FocusGained

    private void tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1FocusGained

    }//GEN-LAST:event_tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1FocusGained

    public void fillForumWithPost() {
        //Gets all the posts in an ArrayList.
        allPostsList = infDB.fillForums();

        //Clears all the windows.
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setText("");
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setText("");
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setText("");
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setText("");
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setText("");
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setText("");
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setText("");
        
        

        //Prints out all the posts packages.
            System.out.print(allPostsList.get(1));
         if (allPostsList.containsKey(1)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow.setText(allPostsList.get(1));
        }
        if (allPostsList.containsKey(2)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow.setText(allPostsList.get(2));
        }
        if (allPostsList.containsKey(3)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow.setText(allPostsList.get(3));
        }
        if (allPostsList.containsKey(4)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow.setText(allPostsList.get(4));
        }
        if (allPostsList.containsKey(5)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow.setText(allPostsList.get(5));
        }
        if (allPostsList.containsKey(6)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow.setText(allPostsList.get(6));
        }
        if (allPostsList.containsKey(7)) {
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll.setText(allPostsList.get(7));
        }


    }

    //Checks what access the user has towards current login and locks down
    //the parts which are access=false.
    private void lockPostRights() {
        boolean eduPoster = CurrentLogin.isUtbildning();
        boolean resPoster = CurrentLogin.isForskning();

        if (!eduPoster) {
            btn_Main_MainMiddleWindow_Research_MainPane_Education.setEnabled(false);
        }
        if (!resPoster) {
            btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost.setEnabled(false);
            btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost.setEnabled(false);
            btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost.setEnabled(false);
            btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost.setEnabled(false);
            btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost.setEnabled(false);
            btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost.setEnabled(false);
        }
    }
    
    
    /**
     * This method takes in the PersonID of the logged-in user.
     * It will check in the TimeChoices table to see if this user is there.
     * It will return a boolean 'true' / 'false' answer.
     * @param thisID
     * @return 
     */
   /*public boolean isUserInTimeChoicesTable(int thisID) {
       boolean personExistsInTable = false;
       String sql = "select MEETING_TIMEID from TIME_CHOICES where PERSONID = " + thisID;
       //personExistsInTable = infDB.isPersonInTimeChoicesTable(sql);
       return personExistsInTable;
     }
    */
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Main_Avsluta;
    private javax.swing.JButton btn_Main_Education;
    private javax.swing.JButton btn_Main_Loggaut;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_Education;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_Social;
    private javax.swing.JButton btn_Main_Research;
    private javax.swing.JButton btn_Main_SkapaMote;
    private javax.swing.JButton btn_Main_Social;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel pnl_MainMiddleWindow_Forskning;
    private javax.swing.JPanel pnl_MainMiddleWindow_Social;
    private javax.swing.JPanel pnl_MainMiddleWindow_Utbildning;
    private javax.swing.JPanel pnl_Main_MainBackgroundPanel;
    private javax.swing.JPanel pnl_Main_MainMiddleWindow;
    private javax.swing.JPanel pnl_Main_TopBorderMenu;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Education_MainPane;
    private javax.swing.JTabbedPane tpn_Main_MainMiddleWindow_Education_MainPane1;
    private javax.swing.JTabbedPane tpn_Main_MainMiddleWindow_Research_MainPane;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow6;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow7;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindowAll;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_ForumWindow;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_ForumWindow;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_ForumWindow;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_ForumWindow;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6;
    private javax.swing.JTextArea tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_ForumWindow;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroupAll;
    private javax.swing.JTabbedPane tpn_Main_MainMiddleWindow_Social;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Social_Pane1;
    // End of variables declaration//GEN-END:variables

    
}
